### ISSUE TITLE
add cmd args

### ISSUE THREAD

**Issue by noga-dev** [mmvergara/supabase-schema-dart-class-generator#6]
`-h, --help` missing

1. Need to be able to specify .env path/name (e.g. .env.dev) via `--path`
2. Allow directly setting supabase url and anon key via `--url` and `--key` args

**Comment by mmvergara** [comment]
As per [1.1.0](https://pub.dev/packages/supadart)

```bash
-h, --help        Show usage information
-e, --env-path    Path to the .env file -- (default: .env)
-u, --url         Supabase URL          -- (default: .env SUPABASE_URL)
-k, --key         Supabase ANON KEY     -- (default: .env SUPABASE_ANON_KEY)
-o, --output      Output file path      -- (default: lib/generated_classes.dart)
```
let me know if you have any problems.. 🙏

**Comment by noga-dev** [comment]
```-v, --version```

and lgtm 👍

**Comment by mmvergara** [comment]
As per [1.2.0](https://pub.dev/packages/supadart)

Added `--version` option and `-d` for dart class version only instead of flutter version
