### ISSUE TITLE
Separate each model into its own file

### ISSUE THREAD

**Issue by noga-dev** [mmvergara/supabase-schema-dart-class-generator#9]
```-o``` should specify just the output folder not the file itself.

And/or add a new arg to separate each class into its own file?

**Comment by mmvergara** [comment]
The current implementation in supabasejs for typescript-types puts them all in 1 file, im trying to make it just the same as that

as for 
> And/or add a new arg to separate each class into its own file?

I'll look onto it!. its doable

**Comment by noga-dev** [comment]
![image](https://github.com/mmvergara/supabase-schema-dart-class-generator/assets/2067558/3b3b0438-0213-4fc4-accc-e484136d5216)

Hmm

I assume it's not possible for the generator to know that the class UserLessons is a reference so instead of User class containing a lesson_id that it should instead contain the referenced Lesson class directly?

Also, the name User_lessons should prob be UserLessons or UsersLessons as this is a many-to-many table. Although I guess I might need to change the name on my end from user_lessons to users_lessons.

**Comment by mmvergara** [comment]
@noga-dev 
> Also, the name User_lessons should prob be UserLessons or UsersLessons as this is a many-to-many table. Although I guess I might need to change the name on my end from user_lessons to users_lessons.

There are a lot of ways a tablename or a filename could go wrong, so i just captalized the first character
```ts
const className = tableName.charAt(0).toUpperCase() + tableName.slice(1);
```


> I assume it's not possible for the generator to know that the class UserLessons is a reference so instead of User class containing a lesson_id that it should instead contain the referenced Lesson class directly?

yeah so relations are one thing that is going to be hard here. but you see in cases where we don't want to get the reference and just the id, there is no way we can insert or update no? I know js has those typescript gymnastic to make up for it but let alone dart i would argue is going to really hard todo, or do you have something in mind that we can do?

**Comment by noga-dev** [comment]
Based on [this](https://supabase.com/docs/guides/database/joins-and-nesting?queryGroups=language&language=dart) page I assume it'll require new arguments in the CLI.

**Comment by mmvergara** [comment]
@noga-dev 

How about doing it like this? i think this is much more explicit and safe.

![image](https://github.com/mmvergara/supabase-schema-dart-class-generator/assets/104471209/3f00dd39-80ba-4b24-9a51-c8903b582a04)

Pros:
- Typesafety
- Explicit and straight forward conversion
- Can support nested relations

Cons:
- Adds 1 line of code
- Some columns are ghost columns and you will be forced to require, required columns in Author as the `fromJson` will fail

**Comment by noga-dev** [comment]
As far as I'm concerned it's alright but would be good to have other devs weigh in.

**Comment by mmvergara** [comment]
@noga-dev  thanks, continued here
https://github.com/mmvergara/supabase-schema-dart-class-generator/issues/17
